[head] Step3. 서버환경과 기능추가
code-squad/javascript-web-todo pull request #10
Opened 2019-03-26 08:12 UTC by HTMLhead

* preview입니다. (https://htmlhead.github.io/javascript-web-todo-production/).

* 코드맥락
* 서버코드
1. heroku를 사용해 제작하였습니다.
1. json 파일을 손수 만들고 res.json()메서드로 json데이터 를 보내주도록 만들었습니다.

* react코드
1. 리뷰 해주신대로 최대한 작게 나누어보았습니다.
1. 불필요한 돔 접근을 모두 제거하였습니다. class를 status의 상태에 따라 집어넣고 빼고 해줄 수 있도록 만들었습니다.
1. 삼항 연산자를 적극적으로 사용하였습니다.
1. tasks데이터 내부의 status를 조작하여 todo 인 일과 done 인 일들을 구분하게 만들었습니다.
1. 그 상태를 사용하여 status-board를 조작하고, 한 일과 할 일들을 따로 tasklist 에 렌더링 되도록 만들었습니다.

* 느낀점 
1. app쪽의 render부분의 코드가 너무 길고, 지저분하다고 느껴집니다. 점심시간에 반에게 물어보았는데, {...this.props}를 사용해서 props 의 내용을 줄이는 것이 효과적이라고 조언을 해주었습니다. 이에 대해 크롱의 생각은 어떠신지 여쭈어보고싶네요 ㅎㅎ
1. context API는 다음스텝에서 적용해보도록 하겠습니다 😸

2019-03-27 06:33 UTC, crongro approved these changes
잘 하셨음. 기능이 꽤 추가되면서 복잡한형태가 되가면서, 고민이 많았을 거 같아요.
그래도 자신있게 구현한 코드로 보여서 좋았어요.
리뷰남긴거 빼고 정말 다 잘했음.

2019-03-27 06:33 UTC, nigayo commented on src/js/App.js
> +  MakeTodoDom,
이름이.. dom이라는 건 그냥 일반적인 document object model이라는 것이니까 다른이름으로.
template을 줄여서 tpl , 또는 jsx 이런게 일반적으로 쓰는 거 같아요.

2019-03-27 06:33 UTC, nigayo commented on src/js/App.js
>        <div className="todo-app-conatiner">
app.js는 최상위컴포넌트임으로, 하위의 컴포넌트를 간단히 표현하면 더 좋죠.

이런식으로
```javascript
 <div className="todo-app-conatiner">
   <TodoStausView />
   <TodoInputView state={this.state} initTask={this.initTask} handleChangeWord={this.handleChangeWord} />
   <TodoListView />
 </div>
```

2019-03-27 06:33 UTC, nigayo commented on src/js/App.js
> +    let hidingClass = ['todo-list-container'];
class이름이 하위컴포넌트에서만 사용하는 것이면, 그곳에서 정의해서 사용해도 될 듯.

2019-03-27 06:33 UTC, nigayo commented on src/js/App.js
> +            state={this.state}
state는 일반적으로 컴포넌트내의 내부 state에서 사용함으로, 속성이름으로 별로네요.
반드시 수정해야 함.

2019-03-27 06:33 UTC, nigayo commented on src/js/change-status-task.js
> +    const tasks = this.props.state.tasks.map(v => v);
destructuring을 잘 활용하면 props의 값을 쉽게 받을 수도 있을 듯.

2019-03-27 06:33 UTC, nigayo commented on src/js/fetch-data.js
> +    console.log(err);
보다 엄격한 에러테스트 해보세요.
404라던가 네트워크 장애라던가, 그때  catch로 에러가 잘 잡히는지도  테스트해보시고, 
적절한 어떻게 에러조치를 하는 것도 해보시고요.

2019-03-27 06:33 UTC, nigayo commented on src/js/fold-task.js
> +    this.foldTask = this.foldTask;
이건 의미없는 코드같아요.
나 = 나;

2019-03-27 06:33 UTC, nigayo commented on src/js/fold-task.js
> +      <button className={this.props.className} onClick={this.foldTask}>
onClick = {this.props.handleBFolded} 해도 될 듯?

2019-03-27 06:33 UTC, nigayo commented on src/js/inputer.js
> +        <button className={this.props.className[1]} onClick={this.addTask}>
0, 1 이라고 하면 그게 무엇인지 잘 모를 거 같네요.
객체나 Map을  쓰는게 더 나을 듯.

2019-03-27 06:33 UTC, nigayo commented on src/js/status-board.js
> +    tasks.forEach(v => {
filter를 쓸 수도 있을 거 같아요.

2019-03-27 06:38 UTC, crongro requested changes
그런데, 요번에 리뷰드린 거 수정해서 보내주세요.

2019-03-27 10:24 UTC, HTMLhead commented
리뷰주신 사항 모두 수정해보았습니다. 현재 서버에서 status Code를 500으로 변경해놓은 상태입니다.
App을 최대한 심플하게 변경하는데 주를 두고 수정하였습니다. 
object spread operator를 사용해보려고 했으나, 막상 사용해보려고하니 제가 생각했던 방식과는 달라서 (한번에 state, method모두를 props로 넘겨버리는 형태) 그냥 모두 props로 넘겨주었습니다

state라는 이름이 아닌것 같아서 taskState로 념겨주긴하였는데, state를 이렇게 전부 props로 옮기는 것이 나쁜 것인가요?
못난코드 읽어주셔서 감사합니다 ㅠㅠ
리뷰 부탁드립니다! 🆘

2019-03-28 01:56 UTC, crongro approved these changes
수고하셨네요.
잘했음요~

2019-03-28 01:56 UTC, nigayo commented on src/js/App.js
> +        <StatusBoard tasks={[...this.state.tasks]} />
👍

2019-03-28 01:56 UTC, nigayo commented on src/js/make-tpl.js
> +import React from 'react';
파일이름에 함수처럼 동사를 넣지 말고 명사로만 ^^

2019-03-28 01:56 UTC, nigayo commented on src/js/make-tpl.js
> +const MakeAlarmTpl = props => {
여기 make-tpl 은 모두 함수형 컴포넌트인데요.

이건 원칙적으로는  개별 파일 단위로 만드는 게 좋아요.

다만 예외적으로 어 너무 비슷한 녀석들이다! 싶을때는 이렇게 모아둘수도 있을거 같아요.
하지만 함수형 컴포넌트별로 별도 파일단위로 분리하는 게 더 권장되는 방법입니다.

2019-03-28 01:56 UTC, merged