Web Todo(React) step3 (서버환경과 기능추가)
code-squad/javascript-web-todo pull request #11
Opened 2019-03-26 11:01 UTC by cocoa-salon

- 할일 삭제 외에 완료 기능을 추가로 구현하였습니다.
- 삭제, 완료에 따른 업데이트는 하나의 메소드에서 처리하여 중복을 줄이고자 하였습니다.
- 특정 컴포넌트 내에서만 사용되는 스타일은 해당 컴포넌트 내에서 정의하였습니다. 

감사합니다.

2019-03-27 07:53 UTC, crongro requested changes
구두로 말씀드린 부분위주로 수정하시면 좋을 거 같아요.

2019-03-27 07:53 UTC, crongro commented on myapp/app.js
> +app.all('/*', function(req, res, next) {
모든 url에 불필요하게 header설정을 해줄필요는 없을 거 같아요.
필요한 url요청에 대해서만 cors설정을 해주세요. 

그리고 express에서 쉽게 cors를 해주는 방법도 있긴할거에요.

2019-03-27 07:53 UTC, crongro commented on myapp/app.js
> +  next(createError(404));
404 잘 되는지 한번 테스트해보세요.

2019-03-27 07:53 UTC, crongro commented on myapp/routes/index.js
> +router.get('/getTodoList', function(req, res, next) {
router분리해서 잘 구현했어요.

2019-03-27 07:53 UTC, crongro commented on src/App_AddTodo_AddTodoButton.js
> +import React from 'react';
파일네이밍이 좀 어색합니다.
Add가 두번이나 들어가기도 하고요.
react 다른 프로젝트 네이밍도 살펴보시고, 언더바를  많이 쓰는지도 한번 들여다보세요.

2019-03-27 07:53 UTC, crongro commented on src/App_TodoListView_DoneTodoButton.js
> +import React from 'react';
```
App/
    components/
         Todolist/
             mainview.jsx
             doneTodoButton.js
```

이런체계도 좋을 거 같네요.

2019-03-27 07:53 UTC, nigayo commented on src/App_TodoScore.js
> +function TodoScore(props) {
destructuring해서 쓰면 좀더 깔끔할 듯.

2019-03-28 03:15 UTC, cocoa-salon commented on myapp/app.js
> +  next(createError(404));
지정된 루트 외에 다른 주소 요청시 404 에러를 발생시킵니다.

2019-04-01 00:39 UTC, crongro approved these changes
컴포넌트 분리가 잘 됐네요!
잘했습니다.

2019-04-01 00:39 UTC, nigayo commented on src/App/components/TodoMain/TodoMain.js
> +        const todoLiElement = this.state.todoList.reduce((accumulator, todo) => {
잘했어요. 이부분도 할일이 많아지면 역시 함수로 분리가능하겠죠.

2019-04-01 00:39 UTC, nigayo commented on src/App/components/TodoMain/TodoList.js
> +function TodoList(props) {
function component  활용을 잘했네요.

2019-04-01 00:40 UTC, merged