[wook] Step18 리뷰 부탁드립니다.
code-squad/javascript-web-todo pull request #27
Opened 2019-08-21 11:11 UTC by dxvinci

## 구현사항
- contextAPI와 useReducer를 이용한 구현
- CRA를 webpack으로 변경
- express 대신 github로 호스팅 

## 느낀점
### 1.  state를 제어하는 함수들은 줄일 수 없으며 어떻게 정리할것인가가 포인트
이전에 캐러샐 미션에서 controller가 비대해지는것과 비슷한 느낌이었습니다. 
initialState에 todos 와 newTodo를 등록했기에 useReducer크기가 todos만 바꾸는것에 비해 훨씬 더 비대해졌습니다. newTodo는 input이 바뀔때마다 랜더링이 되므로 이렇게 코드를 짜면 랜더링이 훨씬 더 많이 일어난다는 문제점이 있지만.. 

### 2. 무엇을 props로 넘겨줄것인가
부모 - 자식과 같은 1단계면 props로 넘겨주는게 좋을것같습니다.  미션에서는 의도적으로 props를 안넘겨주려고 노력했습니다. 
(제가 멍청해서 ㅎㅎ... 수업에서 여쭤보았던것처럼 map함수의 index도 dispatch를 사용하면 넘겨줄 필요가 없었는데...그건 넘겨버렸습니다.. )  

### 3. 디버깅
가끔 에러가 나오는데 어디에서 틀렸는지를 안알려주는 경우가 있었습니다. 감으로 이것저것 바꿔주면서 원인은 못찾고 현상은 해결을 했는데...(문제상황을 표현하기가 어렵네요 ㅜ )  원리를 좀 더 공부해야겠다는 생각이 들었습니다. 

##  데모링크 
https://dxvinci.github.io/react-todo/dist/
read 용 API는 github hosting으로도 가능하다는것을 구글링으로 찾아서 요걸로 배포해보았습니다 ㅎㅎ

changeRequest 받을 준비가 되어있씁니다 ㅎ..... 감사합니다! 🙇‍♂️

2019-08-21 21:29 UTC, crongro commented
깨달은 것처럼 dispatch만을 전달할 때 장점이 있더라고요. 

디버깅은 도구를 익히는 것도 중요해요. React의 디버깅방법을 밀도있게 알아두고, 디버깅을 통해서 문제의 원인을 찾는 습관일 갖는 게 중요해 보여요.

2019-08-21 22:01 UTC, crongro requested changes
학습에 필요한 부분을 코드에 다 담았네요. 잘했어요. context/reducer를 잘 섞어서 썼어요.
hooks에 대한 이해가 좀 올라가셨기를~

전체적인 naming은 좀더 신경써보세요.

Component이름, 디렉토리이름 등도요.
예) 
Output 디렉토리라는 이름은 배포용 디렉토리 같아보여요.

2019-08-21 22:01 UTC, crongro commented on package.json
> +    "@babel/cli": "^7.5.5",
'^' 이 의미하는 건 뭘까요? 
공부하고 모듈 업데이트관련해서 왜 '^' 이런 것이 것이 필요한지 깨달음을 얻으시길~

모듈 업데이트는 유지보수할때 중요해요.

2019-08-21 22:01 UTC, crongro commented on src/Output/OutputTable.js
> +const Table = styled.div`
Table 이라는 이름을 파일명에도 쓰고 했는데, 이게 잘 안쓰이는 이름이라 의도를 알기 어렵네요.
Table은 표를 뜻하니까, 표형태의 UI라고 생각할 수 있을거 같아요. 실제로 table 태그도 존재하기도 하고요.

2019-08-21 22:01 UTC, crongro commented on src/TodoTable.js
> +      case "add":
reducer 구현 잘 했네요. 
immutable 의 장점을 깨닫고(shallow equality check가능) 그렇게 코딩계속해보세요.

action은 변수명과는 다르게 구분하는게 좋아요. 상수처럼 다루는 게 좋아서 대문자로 많이 표현하곤 해요.
'ADD_TODO' , 'CHANGE_TODO_STATUS'  등

2019-08-21 22:01 UTC, crongro commented on src/TodoTable.js
> +      if (data.statusCode === "404")
404 처리는 좋고요. 다른 status code에 대해서도 방어적으로 처리해보는 것도 좋겠죠.

2019-08-21 22:01 UTC, crongro commented on src/TodoTable.js
> +      "https://dxvinci.github.io/react-todo/todolist.json"
API주소는 로직과 관련없는 부분임에도, 자주 변경될 수 있죠. (실무에서는 test API, real API주소가 있곤해요)

이런 부분을 동적으로 변경할수 있도록 하려면 
javascript파일로 config.js 에 넣어줄 수도 있겠고, 
그것보다는 환경설정파일을 활용해서 webpack 빌드단계에서 변경시킬 수도 있을거에요.

2019-08-21 22:01 UTC, crongro commented on src/TodoTable.js
> +  const todosReducer = (state, action) => {
todosReducer 의 코드가 커다랗다면, 분리하는 것도 방법이겠죠. 
파일네이밍을 잘 구분되게 짓고요.

2019-08-21 22:01 UTC, crongro commented on src/components/RadiusDisplayer.js
> +    css`
속성 하나는 css` 하지 않고, 위에 background 처럼 할 수 있는거 같네요.

2019-08-21 22:01 UTC, crongro commented on src/components/RadiusDisplayer.js
> +const Div = styled.div`
Div라는 이름은 진짜별로 인데요. 맥락이 없는 이름이라서 그래요.
이놈의 역할이 무엇인지 생각해서 그걸로 이름을 지어보세요.

2019-08-21 22:01 UTC, crongro commented on src/Output/OutputTable.js
> +    <Background>
만약 여기에 다른 CSS 스타일 속성이 추가되면 Background라는 이름어 거짓이 될 거 같고..
차라리 <TableWrapper> 라는 이름이 더 나을 거 같네요.

2019-08-21 22:01 UTC, crongro commented on src/state.js
> +import React, { createContext, useContext, useReducer } from "react";
state.js 도 너무 일반적인 이름이죠.
의도와 맥락을 생각하면서 네이밍을... 

실제로 
import { useStateValue } from "../state"; 
이렇게 부르면 어떤 state를 사용하는 것인지 의도를 알수가 없죠.

2019-08-21 22:01 UTC, crongro commented on src/state.js
> +export const StateContext = createContext();
context부분을 분리해서 관리하는 게 좋아보이네요.

2019-08-21 22:01 UTC, crongro commented on src/Header/InputBar.js
> +  const handleChangeInput = ({ target: { value } }) => {
디스트럭츄링도 잘했네요 드디어 ㅎ

useReducer를 잘 쓰고 있어서 좋네요.

2019-08-21 22:01 UTC, crongro commented on src/TodoTable.js
> +      "https://dxvinci.github.io/react-todo/todolist.json"
FetchUrl을 보니, DefinePlugin 을 사용하긴 했네요!!

2019-08-21 23:31 UTC, dxvinci commented on package.json
> +    "@babel/cli": "^7.5.5",
tilde (~) and caret (^)
https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json

지원가능한 버전의 범위를 나타냅니다.

2019-08-21 23:49 UTC, dxvinci commented on src/TodoTable.js
> +      if (data.statusCode === "404")
다른 status code는 어떤 경우에 에러가 나는지 경험해보아야 이해할 수 있을것같습니다 ㅠㅠ 
바로 떠오르는 코드로는 500번대가 있는데..요.

사실 저렇게 방어적으로 처리를 해도 잘못된 url로 작성을 할시 (물론 이경우에는 url자체가 잘못되서 이런 에러가 생기는것이지만) 
![image](https://user-images.githubusercontent.com/43375739/63475844-89b75c80-c4b9-11e9-9d1a-93721bd5e3d1.png)

경험해보지 못해서 와닫지가 못하는것같습니다..

2019-08-22 00:56 UTC, dxvinci commented on src/components/RadiusDisplayer.js
> +const Div = styled.div`
이름 생각하는게 너무 어려워서 그냥.. html 태그명을 가져다 쓰려고 했습니다 ㅠㅠ 애매한 맥락보다는 명시적인 div가 더 나을수도 있다구 생각해서요...ㅎ...

2019-08-22 23:43 UTC, crongro commented on package.json
> +    "@babel/cli": "^7.5.5",
설정에 따라서, 
업데이트 할때 어디까지 자동으로 업데이트가 되는 것인지 알아둘 필요가 있어요.

2019-08-26 00:46 UTC, dxvinci commented
말씀해주신 수정사항 변경하였습니다. 다시 리뷰 요청부탁드립니다 ㅎㅎ 🙇‍♂️

1. 변수명 변경
2. state변경 : todoReducer의 newTodo를 InputBar의 내부 state로 관리하도록 변경
3. todoReducer 함수를 TodoApp이 아닌 다른 파일에 위치하도록 분리
4. 로딩상태에 따른 조건부 랜더링 가능하도록 구현
- ResultBar의 status출력 조건에 따라 실행가능하도록 calcStatusCnt 구현
- TodoList의 makeTodoList구현 
5. useFetch 커스텀 훅 생성

2019-08-26 05:45 UTC, crongro approved these changes
네이밍 위주로 모두 수정이 잘 된 거 같네요. 👍 

좋은코드는 의도를 잘 드러내는데요. 
뭐 자주 봐야죠.

오픈소스등 남의코드를 읽는 활동을 해보세요.
그런 스터디도 좋고요.

2019-08-26 05:45 UTC, merged