[wook] Step19 리뷰 부탁드립니다.
code-squad/javascript-web-todo pull request #34
Opened 2019-09-01 13:14 UTC by dxvinci

## 1. 진행사항
### 1. Proptypes 반영 
- Todoitem 
- StateProvider 

### 2. react-router 를 활용하여 메뉴탭 구성
- About , Home 컴포넌트는 jsx로 만듦( js 벗어나고 싶어서 ㅎ.ㅎ jsx가 코드짤때 더 편한것같습니다. 단축키가 지원되서요..) 
### 3. useMemo , useCallback , + 각종 성능개선
- Profiler탭을 확인해보며 개선하려고 했으나.. 제가 짠 코드에서는 useMemo와 useCallback을 사용하여 개선할 
수 있는 부분이 없었습니다. 
https://ideveloper2.dev/blog/2019-06-14--when-to-use-memo-and-use-callback/
- TodoState의 Provider 구조를 변경하여 useMemo를 사용하지 않고 컴포넌트의 랜더링횟수를 줄였음.
https://kentcdodds.com/blog/how-to-optimize-your-context-value
- React.memo를 이용하여 todo들의 리랜더링 막음

## 2. 아쉬운 점
- react-router를 이용하여 메뉴탭을 구현하였지만 Route 컴포넌트의 props인 history,match,location을 사용할 부분이 없어서, 공부하지 않았고 너무 react-router를 대충쓰고 넘어간것같아서 아쉽습니다  
- Profiler 탭에서 무엇에 의해 render 되는지 알면 더 좋을듯한데 어떻게 알아봐야할지 몰라서 ㅎㅎ... console찍어서 확인하였습니다 
- useCallback과 useMemo를 사용하기에 적절한 사례가 아니었던것같습니다. (contextAPI를 사용했기에 props로 값이나 함수를 넘겨주지 않기때문)
- Profiler 탭에서 reload하고 재실행할때마다 시간이 다르게 측정되어 최적화가 됬는지 확인하기 어려웠습니다

## 3. 느낀점
- 라우팅을 적용하고싶은데 많이 파지 못했고 더 공부해보고싶은데 적절한 예시가 무엇이 있을지 모르겠습니다.
- 최적화는 재미있는것같은데, profiler 로 레코딩을 할때마다 시간이 다르게 나와서.. 어떻게 동일한조건으로 맞춰주고 측정해야할지 모르겠습니다. 그냥 탭에서 색깔보면서 리랜더링 유무를 파악한.. 무식한 방법을 사용한것같습니다.
- Proptypes 가 이미 정해져서 넘어오는 값이라서 그런지.. 사용했을 때의 큰 이점이 무엇일지 모르겠습니다. 

감사합니다! 🙇‍♂️

2019-09-02 07:48 UTC, crongro requested changes
먼저 여러가지 적용을 위한 시도가 좋네요.성능개선을 위한 고민도 보이고요.

라우터는 아직 복잡한 애플리케이션이 아니라서 그럴수 있어요. 
인증등이 포함되면 redirect도 하고 그러면서 좀더 다양한 기능을 쓸 수 있겠죠.

성능개선도 역시복잡도가 올라갈수록 그 의미가 크죠. 어떤 부분을 왜 개선해야할지 고민하고 그 효과를 가급적 확인하는 게 좋아요. 개발자도구의 component / profiler 패널을 좀더 들여다보시죠. 

그리고 기능을 버그가 좀 있어요.
- 처음 접속하면 아무것도 노출되지 않는 문제
- 완료된 일로 표시하고, HOME에 갔다가 다시 할일목록으로 오면 완료표시가 안되는 문제.
요건 버그라서 수정을 하고 넘어가면 좋겠어요.

2019-09-02 07:48 UTC, crongro commented on src/Home.jsx
> +      color: hotpink;
(핫핑크..)

2019-09-02 07:48 UTC, crongro commented on src/StateHelper/TodoState.js
> +    <TodosStateContext.Provider value={todos}>
context를 여러새 중첩된 코드로 만든 이유가??? 
불필요하게 랩핑된 객체가 많아진 결과라서 디버깅도 어렵고 장점이 없을거 같아요.

2019-09-02 07:48 UTC, crongro commented on src/Todo/Header/ResultBar.js
> +  const todos = useTodosStateValue();
useContext를 여기서 직접 부르는 것과 달리, 이코드가 어떤 장점이 있는지 전 잘 모르겠어요.
괜한 함수하나를 더 둔거 같기도같고요. 장점이 뭘까요?

2019-09-02 07:48 UTC, crongro commented on src/Todo/Header/ResultBar.js
> +  const countStatus = status => {
큰  차이는 아니겠지만, 이런코드를 useMemo로 결과를 캐시하면 어때요?

2019-09-02 07:48 UTC, crongro commented on src/Todo/TodoList.js
> +        {isLoading === true && <li>로딩중...</li>}
true와 비교는 필요가 없겠죠.

{isLoading && <li> 로딩중...}

2019-09-02 07:48 UTC, crongro commented on src/TodoApp.js
> +    <Router>
Router기능은 별거 없어요.
SPAs가 더 복잡한 상태가 된다면 router기능도 좀더 활용하게 되겠죠.
예를들어 인증이 붙는다던가 등등

2019-09-02 07:48 UTC, crongro commented on src/TodoApp.js
> +        <Route exact path="/home" component={Home} />
참고로,
Switch 컴포넌트로 라우팅을 하는것과 차이도 알아보세요.
404처리용 라우터도 알아보면 좋고요.

2019-09-02 08:44 UTC, dxvinci commented on src/Todo/Header/ResultBar.js
> +  const countStatus = status => {
리랜더링이 이미 최소한으로 일어나... useMemo를 사용해도 캐싱이 일어나지 않고, 성능개선을 기대할 수 없다고 생각했습니다.
useMemo와 useCallback으로 캐시하는것보다, 리랜더링을 최소한으로 만드는것이 더 중요하다고 생각하였습니다!

2019-09-02 08:46 UTC, dxvinci commented on src/StateHelper/TodoState.js
> +    <TodosStateContext.Provider value={todos}>
value를 {state, dispatch, isLoading} 객체로 만들경우 state와 isLoading이 바뀔때마다 state와 isLoading을 받는 InputBar( 입력에 관한 컴포넌트 ) , ResultBar ( 결과창을 출력하는 컴포넌트) 가 리랜더링이 일어납니다. 
그러나 context를 위와같은 구조로 만들경우 isLoading이 바뀌어도 InputBar는 리랜더링이 일어나지 않습니다. 
여러개 중첩하지 않고 isLoading이 바뀔때 InputBar가 리랜더링이 되지 않게 하는방법이 있는지는 잘 모르겠습니다 ㅠ

2019-09-02 08:58 UTC, dxvinci commented on src/Todo/Header/ResultBar.js
> +  const todos = useTodosStateValue();
일단 개인적인 취향인데요 제가 함수 하나를 더 만든 이유는 
import React, { useContext } from 'react'
import {  TodosStateContext } from "../../StateHelper/TodoState";
로 모듈에서 두 함수를 불러오는것보다 차라리 TodoState에서 useTodosStateValue라는 함수를 만들어서 결과값만 리턴해주는게 더 깔끔하다고 생각했기 때문입니다.

새로운 함수를 만드들고 export 하는것 vs ResultBar.js 에서 두 함수를 Import 하는것의 trade-off라고 생각했습니다. (그런데 처음에 useContext를 공부할땐.. TodoState에서 새 함수를 만들고 export하는게 더 이해가 쉬워서... 이렇게 구현했고 지금도 이렇게 쓰고있는것같습니다 ㅎ....)

2019-09-02 08:59 UTC, dxvinci commented on src/Todo/TodoList.js
> +        {isLoading === true && <li>로딩중...</li>}
`isLoading === true` 이렇게 작성하는게 저는 더 명시적으로 쉽게 보이는것같아서 ㅎ.ㅎ 요렇게 작성하였습니다

2019-09-02 08:59 UTC, dxvinci commented on src/TodoApp.js
> +    <Router>
넵 ㅎㅎ!

2019-09-04 02:12 UTC, crongro reviewed
버그해결하면 커밋로그에 보통 (fix) 라고 표현해요.

2019-09-04 02:12 UTC, crongro commented on client/README.md
> +- 과제가 useCallback과 useMemo를 사용하기에 적절한 사례가 아니었던것같음.
추가할만한 기능하나만 아이디어 좀  주시면 감사..!

2019-09-04 02:20 UTC, crongro approved these changes
버그도 수정하고, 잘 동작되네요.

성능개선을 공부한김에 블로그(?)를 써보는 것을 추천!

2019-09-04 02:20 UTC, crongro commented on server/todoApp.js
> +  res.send({
json응답이면 json을 사용하는 것이 좀더 좋은거 같네요. 
응답헤더에 content-type을 application/json등으로 설정해주는 등의 적절한 조치를 해줄 듯.

2019-09-04 02:20 UTC, crongro commented on server/data/todolist.json
> +{
분리 잘 했음

2019-09-04 02:20 UTC, crongro commented on server/data/todolist.json
> +{
mongo db 연동도 해보면 좋겠죠.
 NoSQL이 연동하기 쉽더라고요.

2019-09-04 02:21 UTC, merged

2019-09-04 03:16 UTC, dxvinci commented on client/README.md
> +- 과제가 useCallback과 useMemo를 사용하기에 적절한 사례가 아니었던것같음.
넵 생각해보겠습니다!

2019-09-04 03:17 UTC, dxvinci commented
> 버그도 수정하고, 잘 동작되네요.
> 
> 성능개선을 공부한김에 블로그(?)를 써보는 것을 추천!



블로그글도 써보겠습니다!

2019-09-04 03:18 UTC, dxvinci commented on server/data/todolist.json
> +{
step 21 인증 하면서 기회가 되면 db도 구현해보겠습니다!